### ISSUE TITLE
Header files

### ISSUE THREAD

**Issue by eastern-grey** [mulbc/homebrew-ceph-client#10]
Thanks for making this!

I'm using a go librados binding, and it requires the header files are available in order to build. Would it be possible to include src/include in futures bottles? I had to grab the source and manually copy the include files into /usr/local/include to be able to get the go binding to build.

**Comment by mulbc** [comment]
Sure! At best you hand in a PR - I'm currently not actively working on this... But happy to accept PRs.

I'm curious though which application you're using with this?

**Comment by eastern-grey** [comment]
It's an internal tool that runs on a Linux box usually - just nice to be able to check the code compiles on a Mac laptop first.

I had a try at updating the recipe, but got stuck as the build was not finding cython, even though it's listed as a build depends and installed. Not a problem if you don't have time to work on it, just thought I'd mention it.
