### ISSUE TITLE
Failed to build and install cython_rados python module

### ISSUE THREAD

**Issue by xxmfxx** [mulbc/homebrew-ceph-client#23]

**Comment by xxmfxx** [comment]
was due to an internal version of brew.

**Comment by KatyuMarisa** [comment]
> was due to an internal version of brew.

Hi, I got the same error on my macOS Monterey 12.5.
My homebrew's version is 3.6.2. I tried to figure this out by checking brew's installation log and I found maybe some cython environment arguments are not passed in correct way, but I have no idea how to handle it. Could you tell me how to fix this error? Thanks a lot.
